version: '3.7'

services:
  postgres-java-security-OAUTH:
    image: postgres
    container_name: postgres-java-security-OAUTH
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data